DROP DATABASE IF EXISTS gamematchdb;
CREATE DATABASE gamematchdb;
USE gamematchdb;
CREATE TABLE user (
	id INTEGER NOT NULL AUTO_INCREMENT,
	userName VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	lat DECIMAL(5, 5) NOT NULL,
	lon DECIMAL(5, 5) NOT NULL,
	favoriteGame VARCHAR(100),
	skillLevel INTEGER NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE rightswipe (
	id INTEGER NOT NULL AUTO_INCREMENT,
	userId INTEGER NOT NULL,
	prospectId INTEGER NOT NULL,
	distance DECIMAL(10, 2) NOT NULL,
	isActive BOOLEAN NOT NULL,
	message VARCHAR(500),
	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
	FOREIGN KEY (prospectId) REFERENCES user(id) ON DELETE CASCADE
);