const { User } = require("../models");

const userData = [
    {
        username: "mikeR",
        password: "123",
        lat: 40.326552,
        lon: -78.993579,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "mikeruanedev2@gmail.com",
        testSize: 1,
        minSkillLevel: 2,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "kyleB",
        password: "123",
        lat: 40.850871,
        lon: -75.375423,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "chinC",
        password: "123",
        lat: 39.527872,
        lon: -79.412438,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "marcoE",
        password: "123",
        lat: 40.939524,
        lon: -75.366335,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "alexC",
        password: "123",
        lat: 41.203797,
        lon: -78.932652,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "andreS",
        password: "123",
        lat: 41.268493,
        lon: -74.500847,
        favoriteGame: "Settlers of Catan",
        skillLevel: 2,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "andrewH",
        password: "123",
        lat: 38.294343,
        lon: -91.256274,
        favoriteGame: "Settlers of Catan",
        skillLevel: 4,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "peteR",
        password: "123",
        lat: 40.650582,
        lon: -74.571131,
        favoriteGame: "Settlers of Catan",
        skillLevel: 5,
        email: "",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "dbAdmin",
        password: "123",
        lat: 39.803326,
        lon: -76.173285,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "mruane@menardgroupusa.com",
        testSize: 1,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser10",
        password: "123",
        lat: 38.8108,
        lon: -91.019428,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser11",
        password: "123",
        lat: 41.818782,
        lon: -80.183499,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser12",
        password: "123",
        lat: 41.128081,
        lon: -79.693927,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser13",
        password: "123",
        lat: 41.248083,
        lon: -75.862869,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser14",
        password: "123",
        lat: 39.594576,
        lon: -80.339977,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser15",
        password: "123",
        lat: 40.30174,
        lon: -80.511585,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser16",
        password: "123",
        lat: 39.598614,
        lon: -78.971615,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser17",
        password: "123",
        lat: 40.632039,
        lon: -75.004747,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser18",
        password: "123",
        lat: 40.704192,
        lon: -74.488239,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser19",
        password: "123",
        lat: 40.455413,
        lon: -77.200943,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser20",
        password: "123",
        lat: 39.963437,
        lon: -74.951033,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser21",
        password: "123",
        lat: 40.152368,
        lon: -80.145414,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser22",
        password: "123",
        lat: 40.289845,
        lon: -77.312848,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser23",
        password: "123",
        lat: 40.489918,
        lon: -78.57571,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser24",
        password: "123",
        lat: 40.488859,
        lon: -74.21797,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser25",
        password: "123",
        lat: 41.055809,
        lon: -80.296792,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser26",
        password: "123",
        lat: 40.482294,
        lon: -74.954953,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser27",
        password: "123",
        lat: 41.069536,
        lon: -75.505321,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser28",
        password: "123",
        lat: 39.110691,
        lon: -92.077971,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser29",
        password: "123",
        lat: 40.092817,
        lon: -74.620326,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser30",
        password: "123",
        lat: 39.815623,
        lon: -79.210229,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser31",
        password: "123",
        lat: 40.87622,
        lon: -80.557829,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser32",
        password: "123",
        lat: 39.549224,
        lon: -80.302034,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 2,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser33",
        password: "123",
        lat: 38.834411,
        lon: -92.547411,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser34",
        password: "123",
        lat: 39.350148,
        lon: -91.128628,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser35",
        password: "123",
        lat: 41.499195,
        lon: -80.786818,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser36",
        password: "123",
        lat: 41.18807,
        lon: -74.539779,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser37",
        password: "123",
        lat: 40.803634,
        lon: -79.59738,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser38",
        password: "123",
        lat: 37.812648,
        lon: -89.13864,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser39",
        password: "123",
        lat: 41.769376,
        lon: -80.127692,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser40",
        password: "123",
        lat: 40.555138,
        lon: -75.969509,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser41",
        password: "123",
        lat: 40.588108,
        lon: -81.109114,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser42",
        password: "123",
        lat: 41.375486,
        lon: -80.235815,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser43",
        password: "123",
        lat: 41.28115,
        lon: -79.826464,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser44",
        password: "123",
        lat: 40.41366,
        lon: -80.526432,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser45",
        password: "123",
        lat: 39.96124,
        lon: -77.014915,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser46",
        password: "123",
        lat: 41.017994,
        lon: -75.356529,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser47",
        password: "123",
        lat: 41.152447,
        lon: -80.983355,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser48",
        password: "123",
        lat: 39.909366,
        lon: -77.296402,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser49",
        password: "123",
        lat: 40.134074,
        lon: -79.215965,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser50",
        password: "123",
        lat: 41.286351,
        lon: -74.708522,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser51",
        password: "123",
        lat: 40.262205,
        lon: -75.579989,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser52",
        password: "123",
        lat: 40.222341,
        lon: -75.17208,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser53",
        password: "123",
        lat: 39.948968,
        lon: -79.911101,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser54",
        password: "123",
        lat: 40.427635,
        lon: -78.77466,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser55",
        password: "123",
        lat: 39.174292,
        lon: -90.039714,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser56",
        password: "123",
        lat: 41.172086,
        lon: -78.878273,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser57",
        password: "123",
        lat: 39.030073,
        lon: -88.935023,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser58",
        password: "123",
        lat: 40.02413,
        lon: -77.223274,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser59",
        password: "123",
        lat: 39.881918,
        lon: -80.336729,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser60",
        password: "123",
        lat: 40.79702,
        lon: -75.64866,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser61",
        password: "123",
        lat: 39.797882,
        lon: -78.973334,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser62",
        password: "123",
        lat: 38.846131,
        lon: -91.35944,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser63",
        password: "123",
        lat: 40.514331,
        lon: -80.682817,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser64",
        password: "123",
        lat: 40.490385,
        lon: -75.470433,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser65",
        password: "123",
        lat: 41.29091,
        lon: -80.493804,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser66",
        password: "123",
        lat: 39.219288,
        lon: -80.618391,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser67",
        password: "123",
        lat: 41.490122,
        lon: -80.84041,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser68",
        password: "123",
        lat: 41.803768,
        lon: -80.32871,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser69",
        password: "123",
        lat: 38.822646,
        lon: -87.963273,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser70",
        password: "123",
        lat: 40.357411,
        lon: -78.980337,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser71",
        password: "123",
        lat: 38.808506,
        lon: -75.679606,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser72",
        password: "123",
        lat: 39.77191,
        lon: -77.247987,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser73",
        password: "123",
        lat: 39.643238,
        lon: -81.16199,
        favoriteGame: "Settlers of Catan",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser74",
        password: "123",
        lat: 40.722785,
        lon: -79.079313,
        favoriteGame: "Settlers of Catan",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser75",
        password: "123",
        lat: 39.283962,
        lon: -80.882514,
        favoriteGame: "Settlers of Catan",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser76",
        password: "123",
        lat: 40.896354,
        lon: -81.385677,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser77",
        password: "123",
        lat: 40.134643,
        lon: -76.726328,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Philadelphia, PA"
    }, {
        username: "testUser78",
        password: "123",
        lat: 41.295139,
        lon: -80.136616,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser79",
        password: "123",
        lat: 38.325825,
        lon: -90.759109,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }, {
        username: "testUser80",
        password: "123",
        lat: 41.025577,
        lon: -80.14456,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Pittsburgh, PA"
    }, {
        username: "testUser81",
        password: "123",
        lat: 33.669445,
        lon: -117.823059,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser82",
        password: "123",
        lat: 39.710835,
        lon: -104.8125,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser83",
        password: "123",
        lat: 32.705002,
        lon: -97.12278,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser84",
        password: "123",
        lat: 39.099724,
        lon: -94.578331,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser85",
        password: "123",
        lat: 35.1175,
        lon: -89.971107,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser86",
        password: "123",
        lat: 39.791,
        lon: -86.148003,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser87",
        password: "123",
        lat: 39.983334,
        lon: -82.98333,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser88",
        password: "123",
        lat: 30.266666,
        lon: -97.73333,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser89",
        password: "123",
        lat: 32.779167,
        lon: -96.808891,
        favoriteGame: "Go",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser90",
        password: "123",
        lat: 37.487846,
        lon: -122.236115,
        favoriteGame: "Go",
        skillLevel: 1,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser91",
        password: "123",
        lat: 35.25528,
        lon: -81.180275,
        favoriteGame: "Go",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser92",
        password: "123",
        lat: 39.823424,
        lon: -77.982716,
        favoriteGame: "Go",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser93",
        password: "123",
        lat: 40.110148,
        lon: -76.113894,
        favoriteGame: "Go",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser94",
        password: "123",
        lat: 41.356721,
        lon: -77.794784,
        favoriteGame: "Go",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser95",
        password: "123",
        lat: 39.942411,
        lon: -76.738805,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser96",
        password: "123",
        lat: 39.146914,
        lon: -77.761076,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser97",
        password: "123",
        lat: 40.122866,
        lon: -76.327327,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser98",
        password: "123",
        lat: 39.064129,
        lon: -77.463871,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser99",
        password: "123",
        lat: 40.87506,
        lon: -76.709461,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Harrisburg, PA"
    }, {
        username: "testUser100",
        password: "123",
        lat: 36.082157,
        lon: -94.171852,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 5,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser101",
        password: "123",
        lat: 32.698437,
        lon: -114.650398,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 3,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "testUser102",
        password: "123",
        lat: 33.580944,
        lon: -112.237068,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 4,
        email: "",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "Test User City, USA"
    }, {
        username: "apiAddedUser1",
        password: "123",
        lat: 39.554921,
        lon: -88.52218,
        favoriteGame: "Dungeons and Dragons",
        skillLevel: 2,
        email: "apiAdded1@fakegmail.com",
        testSize: 3,
        minSkillLevel: 1,
        maxSkillLevel: 5,
        userBio: "",
        City: "St. Louis, MO"
    }
];

const seedUsers = () => User.bulkCreate(userData);

module.exports = seedUsers;